### ISSUE TITLE
'TOX_AVATAR_MAX_DATA_LENGTH' was not declared

### ISSUE THREAD

**Issue by tr37ion** [Tox/qTox#4]
Hi, I get this error:

src/widget/form/profileform.cpp: In member function 'void ProfileForm::onAvatarClicked()':
src/widget/form/profileform.cpp:217:25: error: 'TOX_AVATAR_MAX_DATA_LENGTH' was not declared in this scope
     if (bytes.size() >= TOX_AVATAR_MAX_DATA_LENGTH)
                         ^
src/widget/form/profileform.cpp:226:25: error: 'TOX_AVATAR_MAX_DATA_LENGTH' was not declared in this scope
     if (bytes.size() >= TOX_AVATAR_MAX_DATA_LENGTH)
                         ^
src/widget/form/profileform.cpp:232:33: error: 'TOX_AVATAR_FORMAT_PNG' was not declared in this scope
     Nexus::getCore()->setAvatar(TOX_AVATAR_FORMAT_PNG, bytes);
                                 ^
Makefile:2525: recipe for target 'profileform.o' failed
make: *** [profileform.o] Error 1

Any idea how to fix it?

**Comment by stal888** [comment]
You should open this on the [the real qTox repo](/tux3/qTox)
